### ISSUE TITLE
Maintenance after v1.1 stable release

### ISSUE THREAD

**Issue by unnawut** [omisego/ewallet#775]
Manual work needed:
- [x] Merge `v1.1` branch to master. Thanks @sirn!
- [x] Merge provider_auth/admin_auth controller tests from #773. Thanks @sirn!
- [x] ~Update `.circleci/config.yml` to `v1.2` on master (prepare the image prior + remove all references to `dev-80264b0` builder)~ Done in #771
- [x] Update **`v1.1` branch**'s `docker-gen.sh` to point to `omisego/ewallet:1.1.0` instead of `v1.1-dev`
- [x] Make sure `Mixfile` **on master** are referring to `v1.2.0-dev`
- [x] Make sure docker-related files **on master** are referring to `omisegoimages/ewallet-builder:v1.2`
- [x] Update **`master` branch**'s `docker-gen.sh` to point to `omisego/ewallet:stable` instead of `v1.1-dev` #789
- [x] Sync `v1.1` branch onto master

**Comment by sirn** [comment]
Another manual work, need to change v1.1 in circleci.yml to stable again as well. I think at this point we probably better tag v1.2 for the stable image that we gonna use. I think, if we merge with a merge commit, Git will use that to track to not override `1.1` -> `1.2` changes we apply after.
