### ISSUE TITLE
Handle upgrade to 1.2

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#821]

**Comment by unnawut** [comment]
### TODOs

- [ ] Add upgrade instructions in docs
- [ ] Check migrations for new instances
- [ ] Check migrations for running instances
- [ ] Check seeds
- [ ] Check installation instructions
- [ ] Draft release notes
