### ISSUE TITLE
Make client keys work without master account

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#839]

**Comment by unnawut** [comment]
### TODO:

#### Schemas
- [ ] Delete existing records that are not `owner_app: ewallet_api`
- [ ] Remove APIKey schema's `:account_uuid`
- [ ] Remove `:owner_app` since it's now used only by `ewallet_api`
- [ ] Remove `:exchange_wallet`

#### APIs
- [ ] Remove account assigning from `/api/admin/api_key.create` (currently defaults to master account)
- [ ] Verify that authentication with client key & user credentials still works

### Implications
- Client keys will now work with any account. However they cannot be authenticated alone, and still need to be used with a specific user credentials. Hence its usage will still limited by what the user's permissions.
